version: '3.3'
services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/var/www/node
      - node_modules:/var/www/node/node_modules
volumes:
  node_modules: